services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: train-mssql

    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Train@123

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssql
    
  backend:
   build: ./backend
   ports:
    - "8080:8080"


  frontend:
   build: ./frontend
   ports:
    - "5173:5173"


volumes:
  sql_data: